networks:
  wafnet:
    name: wafnet
    driver: bridge
    ipam:
      driver: default
      config:
      - gateway: 172.31.255.1
        subnet: 172.31.255.0/24
    driver_opts:
      com.docker.network.bridge.name: wafnet

services:
  uuwaf:
   image: swr.ap-southeast-1.myhuaweicloud.com/uusec/uuwaf:latest
   ulimits:
     nproc: 65535
     nofile:
       soft: 102400
       hard: 102400
   container_name: uuwaf
   restart: always
   networks:
      wafnet:
   ports:
     - "80:80"
     - "443:443"
     - "4443:4443"
   volumes:
     - wafshared:/uuwaf
     - /etc/localtime:/etc/localtime:ro
   command: ["/run.sh"]
   environment:
     - UUWAF_MYSQL_PASSWORD=Safe3.WAF

   links:
   - wafdb
   depends_on:
      wafdb:
        condition: service_healthy

  wafdb:
   image: swr.ap-southeast-1.myhuaweicloud.com/uusec/percona-server:5.7
   ulimits:
     nproc: 65535
     nofile:
       soft: 102400
       hard: 102400
   container_name: wafdb
   restart: always
   networks:
      wafnet:
   volumes:
     - wafshared:/docker-entrypoint-initdb.d
     - wafdata:/var/lib/mysql
     - /etc/localtime:/etc/localtime:ro
     #- ./low-memory-my.cnf:/etc/mysql/my.cnf
   environment:
     - INIT_ROCKSDB
     - MYSQL_MAX_CONNECTIONS=512
     - MYSQL_ROOT_PASSWORD=Safe3.WAF
   healthcheck:
     test: ["CMD", "mysqladmin", "-uroot", "-pSafe3.WAF", "ping", "-h", "127.0.0.1", "--silent"]
     start_period: 3s
     interval: 5s
     timeout: 3s
     retries: 7

volumes:
  wafshared:
  wafdata:
