networks:
  wafnet:
    name: wafnet
    driver: bridge
    ipam:
      driver: default
      config:
      - gateway: 172.31.254.1
        subnet: 172.31.254.0/24
    driver_opts:
      com.docker.network.bridge.name: wafnet

services:
  uuwaf:
   image: swr.ap-southeast-1.myhuaweicloud.com/uusec/uuwaf:latest
   ulimits:
     nproc: 65535
     nofile:
       soft: 102400
       hard: 102400
   container_name: uuwaf
   restart: always
   network_mode: host
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - waf_shared:/uuwaf/initdb
     - waf_config:/uuwaf/web/conf
     - waf_acme_accounts:/uuwaf/web/accounts
     - waf_acme_certificates:/uuwaf/web/certificates
   command: ["/run.sh"]
   environment:
     - UUWAF_DB_DSN=root:${MYSQL_PASSWORD}@tcp(127.0.0.1:6612)/uuwaf?charset=utf8mb4&parseTime=true&loc=Local
   depends_on:
      wafdb:
        condition: service_healthy

  wafdb:
   image: swr.ap-southeast-1.myhuaweicloud.com/uusec/percona-server:5.7
   ulimits:
     nproc: 65535
     nofile:
       soft: 102400
       hard: 102400
   container_name: wafdb
   restart: always
   networks:
      wafnet:
        ipv4_address: 172.31.254.3
   ports:
     - "6612:3306"
   volumes:
     - /etc/localtime:/etc/localtime:ro
     - waf_shared:/docker-entrypoint-initdb.d
     - waf_data:/var/lib/mysql
     #- ./low-memory-my.cnf:/etc/mysql/my.cnf
   environment:
     - INIT_ROCKSDB
     - MYSQL_MAX_CONNECTIONS=512
     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
   healthcheck:
     test: ["CMD", "mysqladmin", "-uroot", "-p${MYSQL_PASSWORD}", "ping", "-h", "127.0.0.1", "--silent"]
     start_period: 3s
     interval: 5s
     timeout: 3s
     retries: 10

volumes:
  waf_shared:
  waf_config:
  waf_acme_accounts:
  waf_acme_certificates:
  waf_data:
